"""Seed the ``companies`` / ``personal_colleagues`` / ``personal_appointments`` tables.

This is a straight Python transcription of the demo data that used to live only in
``frontend/src/pages/CompanyWorkspacePage/companyWorkspace.data.ts``. Running this script
replaces the current contents of those three tables with the data below — safe to re-run,
it is not meant to hold real customer data (see ``docs/postgres-docker-setup.md``).

Usage (from the repo root, with the project env active):
    python backend/scripts/seed_company_data.py

Reads DATABASE_URL from .env (defaults to sqlite ./auth.db). Never run this against a
production database.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

from dotenv import find_dotenv, load_dotenv

# Load .env BEFORE importing db.session: the async engine is built from DATABASE_URL at import.
load_dotenv(find_dotenv())

# Allow `backend.app...` imports when run as a plain script (sys.path[0] would be backend/scripts).
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from sqlalchemy import delete  # noqa: E402

from backend.app.db.session import AsyncSessionLocal, run_migrations  # noqa: E402
from backend.app.models.company import Company, PersonalAppointment, PersonalColleague  # noqa: E402

COMPANIES: list[dict] = [
    {
        "id": "aurora-bank",
        "name": "Aurora Bank",
        "segment": "Fintech",
        "last_visited": "10:22",
        "is_favorite": True,
        "assigned_roles": ["admin", "salesConsultant", "analyst"],
        "owner": "M. Ritter",
        "open_questions": 6,
        "completed_questions": 26,
        "pending_meetings": 2,
        "completed_meetings": 9,
        "documents": ["Q2 Risiko-Radar", "Roadmap API Consent", "Journey Mapping v3"],
        "hypotheses": [
            {"text": "Antwortquote steigt mit persona-spezifischen Follow-ups.", "status": "confirmed"},
            {"text": "Dokumenten-Shortcuts reduzieren offene Tickets > 20%.", "status": "confirmed"},
        ],
        "appointments": [
            "W-1 Mo 09:00 Sprint Review | Lena, Amir, Dominic",
            "W-1 Mo 14:30 Kunden-Präsentation | Carla, Jens",
            "W-1 Di 10:00 Technische Abstimmung | Amir, Carla",
            "W-1 Mi 09:30 Journey Workshop | Lena, Carla, Dominic",
            "W-1 Do 15:00 Risiko-Retrospektive | Jens, Amir",
            "W-1 Fr 11:00 Sprint Abschluss | Lena, Amir, Dominic",
            "Mo 08:30-09:00 Daily Standup | Lena, Amir, Dominic",
            "Mo 10:00-11:30 Risk Review | Amir, Jens",
            "Mo 11:00-12:00 Steering | Lena, Amir, Jens",
            "Mo 14:00-15:00 Demo Prep | Carla, Lena",
            "Mo 16:30-17:00 EOD Sync | Amir",
            "Di 09:00-10:30 QBR Vorbereitung | Jens, Carla, Dominic",
            "Di 10:30-11:30 Legal Abstimmung | Jens",
            "Di 13:00-14:00 Produkt-Feedback | Lena, Amir, Carla",
            "Di 15:00-15:30 Client Check-in | Carla",
            "Di 17:00-18:00 Release Planning | Amir, Carla",
            "Mi 08:30-09:00 Daily Standup | Lena, Amir",
            "Mi 09:30-11:30 Roadmap Session | Carla, Jens, Lena, Dominic",
            "Mi 11:30-12:30 API Workshop | Amir",
            "Mi 15:30-16:30 Enablement | Carla, Lena",
            "Mi 16:00-17:00 Budget Review | Jens",
            "Do 09:00-10:30 Strategy Review | Lena, Amir, Jens, Dominic",
            "Do 10:30-11:30 Einwand-Handling | Carla, Lena",
            "Do 14:00-15:00 Risk Assessment | Jens",
            "Do 15:30-16:00 Next Steps | Amir",
            "Fr 09:00-10:00 Sales Review | Amir, Carla, Jens, Dominic",
            "Fr 10:30-11:30 Weekly Close | Lena, Amir",
            "Fr 13:00-14:30 Retro | Carla, Jens",
            "Fr 15:00-16:00 Forecast | Amir, Lena",
            "W+1 Mo 08:30 Sprint Planning | Lena, Amir, Dominic",
            "W+1 Mo 10:00 Risk Monitoring | Amir, Jens",
            "W+1 Di 09:30 Produkt-Roadmap | Carla, Lena",
            "W+1 Di 14:00 Legal Update | Jens, Dominic",
            "W+1 Mi 11:00 Data Review | Amir, Carla",
            "W+1 Mi 14:30 API Consent Sync | Lena, Jens",
            "W+1 Do 10:00 Quarterly Check-in | Lena, Amir, Carla, Jens, Dominic",
            "W+1 Do 15:30 Eskalations-Check | Amir",
            "W+1 Fr 10:00 Weekly Wrap | Amir, Lena",
            "W+1 Fr 13:00 Forecast Prep | Carla, Jens",
            "W+2 Mo 09:00 OKR Review | Lena, Amir, Dominic",
            "W+2 Mo 14:00 Governance Session | Jens",
            "W+2 Di 11:00 Security Audit | Jens, Amir",
            "W+2 Mi 10:30 Feature Preview | Carla, Lena, Dominic",
            "W+2 Mi 14:00 Architecture Review | Amir, Carla",
            "W+2 Do 10:00 Stakeholder-Sync | Jens",
            "W+2 Do 14:30 Release Gate | Lena, Amir, Carla",
            "W+2 Fr 12:00 Monats-Abschluss | Amir, Carla, Dominic",
        ],
        "notes": [
            "Decision Maker will benchmark against two competitors.",
            "Need legal review for data retention wording.",
        ],
        "team_members": ["Sales: Lena", "CSM: Amir", "Solution: Carla", "Legal: Jens"],
        "personas": ["Head of Risk", "Ops Lead", "Data Officer"],
        "newsfeed": [
            "Pilot region expanded to DACH branch network.",
            "Internal KPI target updated to response-time below 2.1s.",
        ],
        "recent_events": [
            "Heute 09:40: Follow-up Meeting geplant.",
            "Gestern: Persona Mapping aktualisiert.",
            "Montag: Dokumenten-Freigabe durch Legal.",
        ],
        "portfolio_summary": "2 aktive Produkte, Upsell-Potenzial im Governance-Paket.",
        "performance_summary": "81% beantwortete Fragen, 14 offen, 2 kritische Follow-ups.",
    },
    {
        "id": "nordlicht-logistics",
        "name": "Nordlicht Logistics",
        "segment": "Transport",
        "last_visited": "09:58",
        "is_favorite": False,
        "assigned_roles": ["admin", "salesConsultant"],
        "owner": "D. Reimann",
        "open_questions": 3,
        "completed_questions": 14,
        "pending_meetings": 1,
        "completed_meetings": 5,
        "documents": ["Fleet AI Review", "SLA Delta 2026", "Renewal Negotiation Notes"],
        "hypotheses": [
            {"text": "Dispatch-Assist Feature senkt Eskalationen in Peak-Slots.", "status": "pending"},
        ],
        "appointments": [
            "W-1 Mo 10:00 Fleet Recap | Daria, Kim",
            "W-1 Di 14:30 SLA Analyse | Faris, Dominic",
            "W-1 Do 09:00 Eskalations-Log | Daria, Kim, Faris",
            "W-1 Fr 11:00 Sprint Review | Kim, Dominic",
            "Mo 09:00-09:30 Fleet-Status | Daria, Kim, Dominic",
            "Di 10:30-12:00 SLA-Abstimmung | Kim, Faris",
            "Di 14:00-15:00 KPI Review | Daria, Faris, Dominic",
            "Mi 11:00-11:30 Eskalations-Check | Faris",
            "Mi 14:30-15:30 Ops-Sync | Kim, Dominic",
            "Do 09:30-11:00 Renewal Prep | Daria, Kim, Faris",
            "Do 15:00-15:30 Wochenbericht | Daria, Faris, Dominic",
            "Fr 09:30-10:00 Fleet Close | Kim",
            "W+1 Mo 09:30 Route Planning | Daria, Kim",
            "W+1 Di 11:00 Renewal Final | Faris, Daria, Dominic",
            "W+1 Mi 10:00 Ops-Update | Kim",
            "W+1 Mi 15:00 Dispatch Review | Daria, Faris",
            "W+1 Do 14:00 KPI Board | Daria, Faris",
            "W+1 Fr 10:30 Wochensync | Kim, Faris, Dominic",
            "W+2 Mo 09:00 Q2 Kick-off | Daria, Kim, Faris",
            "W+2 Mi 11:00 Forecast | Faris, Dominic",
            "W+2 Do 14:00 SLA Board | Daria, Kim",
            "W+2 Fr 09:00 Abschluss-Meeting | Daria",
        ],
        "notes": ["Customer asks for dashboard access by region managers."],
        "team_members": ["Sales: Daria", "CSM: Faris", "Ops: Kim"],
        "personas": ["Head of Dispatch", "Regional Manager"],
        "newsfeed": ["Two new depots are onboarding in Q3."],
        "recent_events": [
            "Heute 08:15: SLA Delta kommentiert.",
            "Gestern: Erster Renewal-Entwurf versendet.",
            "Letzte Woche: Dispatch KPI Flag gesetzt.",
        ],
        "portfolio_summary": "Starke Nutzung im Dispatch, Dokumentenmodul noch gering.",
        "performance_summary": "74% beantwortete Fragen, 6 offen, 1 Termin in Vorbereitung.",
    },
    {
        "id": "cobalt-health",
        "name": "Cobalt Health",
        "segment": "Healthcare",
        "last_visited": "Gestern",
        "is_favorite": True,
        "assigned_roles": ["admin", "analyst"],
        "owner": "S. Nguyen",
        "open_questions": 9,
        "completed_questions": 21,
        "pending_meetings": 3,
        "completed_meetings": 7,
        "documents": ["Compliance Snapshot", "Patient Journey Mapping", "Insights Q1"],
        "hypotheses": [
            {"text": "Mehr Kontextfelder verbessern Relevanz für Medical Persona.", "status": "confirmed"},
            {"text": "Weekly Summary mit offenen Themen reduziert Churn-Risiko.", "status": "unconfirmed"},
        ],
        "appointments": [
            "W-1 Mo 09:00 Compliance Review | Sina, Lea",
            "W-1 Mi 10:30 Patientendaten-Audit | Daniel, Lea",
            "W-1 Do 14:00 Security Sync | Lea",
            "W-1 Fr 11:00 Wochensync | Sina, Daniel",
            "Mo 08:30 Compliance Sync | Sina, Lea",
            "Mo 10:00 Patient Journey Review | Daniel, Sina",
            "Di 09:00 Datenschutz-Check | Lea",
            "Di 14:00 Product Update | Sina, Daniel",
            "Mi 11:00 Risiko-Assessment | Sina, Lea",
            "Mi 15:00 Insights Deep Dive | Daniel",
            "Do 09:30 IT-Security Review | Lea, Daniel",
            "Do 16:00 Product Board | Daniel, Sina, Lea",
            "Fr 10:00 Wochensync | Sina, Daniel",
            "W+1 Mo 08:30 Datenschutz-Sprint | Sina, Lea",
            "W+1 Di 10:00 Produkt-Check | Daniel, Sina",
            "W+1 Mi 14:00 Risiko-Review | Lea, Sina",
            "W+1 Do 09:00 Clinical Update | Daniel",
            "W+1 Fr 12:00 Monats-Abschluss | Sina, Daniel, Lea",
            "W+2 Mo 10:00 Strategie-Sync | Sina, Daniel",
            "W+2 Di 14:00 Audit-Vorbereitung | Lea",
            "W+2 Fr 11:30 Monats-Retro | Sina, Daniel",
        ],
        "notes": ["Need role-based masking for sensitive patient hints."],
        "team_members": ["Analyst: Sina", "CSM: Daniel", "Security: Lea"],
        "personas": ["Medical Ops", "Compliance Lead", "Support Manager"],
        "newsfeed": ["New procurement framework approved for EMEA rollout."],
        "recent_events": [
            "Heute 07:50: Compliance Notiz aktualisiert.",
            "Gestern: Risiko-Hypothese bestätigt.",
            "Montag: Review mit Security Team.",
        ],
        "portfolio_summary": "Hoher Value im Analysebereich, Pilot für Team-Workflow geplant.",
        "performance_summary": "69% beantwortete Fragen, 18 offen, 3 Termine kommende Woche.",
    },
    {
        "id": "greenforge-energy",
        "name": "Greenforge Energy",
        "segment": "Energy",
        "last_visited": "Gestern",
        "is_favorite": False,
        "assigned_roles": ["admin", "customer"],
        "owner": "R. Novak",
        "open_questions": 2,
        "completed_questions": 11,
        "pending_meetings": 1,
        "completed_meetings": 4,
        "documents": ["Grid Overview", "Portfolio Fit", "Executive Summary"],
        "hypotheses": [
            {"text": "Automation bundle should be placed in next offer.", "status": "pending"},
        ],
        "appointments": [
            "Mo 09:30 Budget Sync | R. Novak, Mira",
            "Mi 11:00 Grid Overview | Mira",
            "Do 14:00 Exec Briefing | R. Novak",
            "Fr 10:00 Site Review | R. Novak, Mira",
            "Fr 13:00 Wochensync | Mira",
        ],
        "notes": ["Customer account sees only own entities by default."],
        "team_members": ["Customer Admin: R. Novak", "Advisor: Mira"],
        "personas": ["Plant Manager", "Finance Lead"],
        "newsfeed": ["Leadership announced modernization budget for 2026."],
        "recent_events": [
            "Gestern: Site Review vorbereitet.",
            "Montag: Product fit Dokument abgelegt.",
            "Letzte Woche: Meeting Slot abgestimmt.",
        ],
        "portfolio_summary": "Single-account visibility, moderate upsell readiness.",
        "performance_summary": "88% beantwortete Fragen, 3 offen, stabiler Health-Score.",
    },
    {
        "id": "sunset-insurance",
        "name": "Sunset Insurance",
        "segment": "Insurance",
        "last_visited": "11:36",
        "is_favorite": True,
        "assigned_roles": ["admin", "salesConsultant", "analyst"],
        "owner": "P. Kramer",
        "open_questions": 5,
        "completed_questions": 19,
        "pending_meetings": 2,
        "completed_meetings": 7,
        "documents": ["Claims Overview", "Renewal Draft", "Risk Signals Q2"],
        "hypotheses": [
            {"text": "Persona snippets in claims context improve resolution speed.", "status": "confirmed"},
            {"text": "Compact weekly summary lowers escalation volume.", "status": "unconfirmed"},
        ],
        "appointments": [
            "Mo 08:45 Wochenbriefing | Jo, Mel, Tim",
            "Di 09:30 Claims Sync | Jo, Mel",
            "Di 14:30 Risk Signals Review | Tim",
            "Mi 10:00 Eskalations-Check | Jo",
            "Mi 15:00 Renewal Vorbereitung | Mel, Tim",
            "Do 09:30 Legal Abstimmung | Tim",
            "Do 14:00 Renewal Board | Tim, Jo, Mel",
            "Fr 11:00 Weekly Close | Jo, Mel",
        ],
        "notes": ["Prefers short summaries and explicit risk tags."],
        "team_members": ["Sales: Jo", "CSM: Mel", "Analyst: Tim"],
        "personas": ["Claims Lead", "Operations Manager", "IT Security"],
        "newsfeed": ["Board approved pilot for automated document routing."],
        "recent_events": [
            "Heute 10:10: Review-Notiz hinzugefügt.",
            "Gestern: Renewal Draft abgestimmt.",
            "Montag: KPI-Alert geschlossen.",
        ],
        "portfolio_summary": "Starker Fit im Claims-Workflow, Upsell im Reporting möglich.",
        "performance_summary": "77% beantwortete Fragen, 9 offen, 2 priorisierte Meetings.",
    },
    {
        "id": "nova-commerce",
        "name": "Nova Commerce",
        "segment": "Retail",
        "last_visited": "Heute",
        "is_favorite": False,
        "assigned_roles": ["admin", "salesConsultant", "customer"],
        "owner": "L. Ortmann",
        "open_questions": 4,
        "completed_questions": 18,
        "pending_meetings": 1,
        "completed_meetings": 5,
        "documents": ["Store Rollout Plan", "Support SOP", "Executive Notes"],
        "hypotheses": [
            {"text": "Store-level prompts can reduce ticket handovers by 18%.", "status": "confirmed"},
        ],
        "appointments": [
            "Mo 09:00 Store Briefing | Nia, Rene",
            "Di 11:00 Ops-Sync | Olek, Rene",
            "Mi 10:30 SOP Review | Nia",
            "Mi 13:00 Weekly Ops | Nia, Olek, Rene",
            "Do 15:00 Region-Update | Olek",
            "Fr 09:30 Rollout Check | Nia, Olek",
        ],
        "notes": ["Needs region-level visibility for store managers."],
        "team_members": ["Sales: Nia", "CSM: Olek", "Ops: Rene"],
        "personas": ["Retail Ops", "Regional Lead"],
        "newsfeed": ["Five new stores scheduled for pilot onboarding."],
        "recent_events": [
            "Heute 09:05: Store KPI export geteilt.",
            "Gestern: SOP finalisiert.",
            "Letzte Woche: Pilot-Scope erweitert.",
        ],
        "portfolio_summary": "Gute Nutzung im Tagesbetrieb, Potenzial bei Team-Modulen.",
        "performance_summary": "83% beantwortete Fragen, 5 offen, stabiler Rollout.",
    },
    {
        "id": "polaris-media",
        "name": "Polaris Media",
        "segment": "Media",
        "last_visited": "08:42",
        "is_favorite": False,
        "assigned_roles": ["admin", "salesConsultant"],
        "owner": "A. Weber",
        "open_questions": 7,
        "completed_questions": 17,
        "pending_meetings": 2,
        "completed_meetings": 6,
        "documents": ["Campaign Brief", "Persona Cluster", "Q3 Theme Map"],
        "hypotheses": [
            {"text": "Persona-driven briefing templates increase response precision.", "status": "unconfirmed"},
            {"text": "Faster tagging lowers content QA loops.", "status": "pending"},
        ],
        "appointments": [
            "Mo 09:30 Redaktions-Briefing | Kim, Andre",
            "Mo 14:00 Campaign Kick-off | Pia, Kim",
            "Mo 16:00 Editorial | Pia, Kim",
            "Di 11:00 Content Review | Kim",
            "Di 15:30 KPI-Update | Andre, Pia",
            "Mi 10:00 QA-Loop | Kim, Andre",
            "Do 09:00 Persona-Update | Pia",
            "Do 14:30 Reporting Session | Andre, Kim",
            "Fr 10:00 Stakeholder Sync | Andre, Pia, Kim",
            "Fr 13:00 Wochensync | Pia",
        ],
        "notes": ["Wants explicit confidence hints in recommendations."],
        "team_members": ["Sales: Pia", "CSM: Andre", "Creative: Kim"],
        "personas": ["Editorial Lead", "Campaign Owner"],
        "newsfeed": ["Editorial board approved Q3 experimentation budget."],
        "recent_events": [
            "Heute 08:00: Theme Map aktualisiert.",
            "Gestern: Campaign Brief kommentiert.",
            "Dienstag: Persona Cluster erweitert.",
        ],
        "portfolio_summary": "Hohe Aktivität im Kampagnenbereich, Reporting noch ausbaufähig.",
        "performance_summary": "71% beantwortete Fragen, 11 offen, 2 Fokus-Meetings.",
    },
    {
        "id": "urban-harbor",
        "name": "Urban Harbor",
        "segment": "Real Estate",
        "last_visited": "12:11",
        "is_favorite": True,
        "assigned_roles": ["admin", "customer", "analyst"],
        "owner": "C. Sahin",
        "open_questions": 3,
        "completed_questions": 18,
        "pending_meetings": 1,
        "completed_meetings": 6,
        "documents": ["Tenant Insights", "Portfolio Mix", "Risk Brief"],
        "hypotheses": [
            {"text": "Weekly open-item digest improves board readiness.", "status": "pending"},
        ],
        "appointments": [
            "Mo 10:00 Risk Brief Review | Noor",
            "Di 14:00 Tenant Insights | C. Sahin, Noor",
            "Mi 09:30 Portfolio-Update | Noor",
            "Do 11:00 Portfolio Review | C. Sahin, Noor",
            "Do 15:30 Board Prep | C. Sahin",
            "Fr 10:30 Wochensync | Noor",
        ],
        "notes": ["Customer team requests cleaner handover templates."],
        "team_members": ["Customer Admin: C. Sahin", "Analyst: Noor"],
        "personas": ["Portfolio Manager", "Finance Controller"],
        "newsfeed": ["Two properties moved into modernization planning."],
        "recent_events": [
            "Heute 11:20: Risk Brief überarbeitet.",
            "Gestern: Tenant Insights geteilt.",
            "Montag: Portfolio Mix finalisiert.",
        ],
        "portfolio_summary": "Stark in Portfolio-Transparenz, mittleres Upsell-Potenzial.",
        "performance_summary": "86% beantwortete Fragen, 4 offen, 1 Termin geplant.",
    },
    {
        "id": "lumen-telecom",
        "name": "Lumen Telecom",
        "segment": "Telecom",
        "last_visited": "13:08",
        "is_favorite": False,
        "assigned_roles": ["admin", "salesConsultant", "analyst"],
        "owner": "Y. Baum",
        "open_questions": 8,
        "completed_questions": 20,
        "pending_meetings": 3,
        "completed_meetings": 8,
        "documents": ["SLA Heatmap Q2.pdf", "Incident Playbook.md", "KPI Board v4.xlsx"],
        "hypotheses": [
            {"text": "Automatisierte Priorisierung reduziert MTTD in enterprise queues.", "status": "confirmed"},
            {"text": "Scope-basierte KPI-Slices steigern Cross-Functional Alignment.", "status": "unconfirmed"},
        ],
        "appointments": [
            "W-1 Mo 09:30 Incident Recap | Florian, Dani",
            "W-1 Di 11:00 SLA Analyse | Arda, Mia",
            "W-1 Do 14:30 Eskalations-Review | Florian, Dani",
            "W-1 Fr 10:00 Sprint Abschluss | Mia, Arda",
            "Mo 08:30 Incident Debrief | Florian, Dani",
            "Mo 10:30 Ops Board | Arda, Florian",
            "Mo 14:00 SLA Forecast | Mia",
            "Di 09:00 NOC-Update | Dani, Florian",
            "Di 11:30 KPI Review | Arda, Mia",
            "Mi 10:00 Eskalationsrunde | Florian, Dani",
            "Mi 12:00 Enterprise SLA Sync | Mia, Florian, Dani",
            "Mi 15:00 Team Sync | Arda",
            "Do 09:30 Security Check | Dani",
            "Do 14:00 Cross-Functional | Arda, Mia, Florian",
            "Fr 10:00 Wochenbericht | Mia, Arda",
            "Fr 15:00 Exec Debrief | Arda, Mia, Florian",
            "W+1 Mo 08:30 NOC Planning | Dani, Florian",
            "W+1 Di 11:00 SLA Review | Mia, Arda",
            "W+1 Mi 09:30 Incident Playbook Update | Florian",
            "W+1 Do 14:00 Enterprise Check-in | Arda, Mia",
            "W+1 Fr 10:00 Wochenbericht | Mia, Arda",
            "W+2 Mo 10:00 Q2 Ops Planning | Arda, Florian",
            "W+2 Mi 14:00 KPI Board | Mia, Dani",
            "W+2 Fr 11:00 Monats-Retro | Arda, Mia, Florian",
        ],
        "notes": ["Need confidence gates for automated escalation suggestions."],
        "team_members": ["Sales: Arda", "CSM: Mia", "Ops Lead: Florian", "Security: Dani"],
        "personas": ["Network Ops Lead", "Enterprise CSM", "Support Director"],
        "newsfeed": ["Regional NOC introduced stricter incident classification in all clusters."],
        "recent_events": [
            "Heute 12:20: KPI Board um SLA Risk Layer erweitert.",
            "Gestern: Incident Playbook finalisiert.",
            "Dienstag: Scope-Review mit Ops und Security.",
        ],
        "portfolio_summary": "Breites Rollout-Potenzial, hoher Bedarf an SLA-Transparenz.",
        "performance_summary": "72% beantwortete Fragen, 13 offen, 3 priorisierte Termine.",
    },
    {
        "id": "atlas-automotive",
        "name": "Atlas Automotive",
        "segment": "Automotive",
        "last_visited": "14:16",
        "is_favorite": True,
        "assigned_roles": ["admin", "customer", "salesConsultant"],
        "owner": "J. Haller",
        "open_questions": 5,
        "completed_questions": 19,
        "pending_meetings": 2,
        "completed_meetings": 8,
        "documents": ["After-Sales Intelligence.pdf", "Factory Rollout Plan.pptx", "Escalation Matrix.csv"],
        "hypotheses": [
            {"text": "Persona-spezifische Serviceantworten senken Rework in Dealer-Teams.", "status": "confirmed"},
        ],
        "appointments": [
            "Mo 09:30 Service-Briefing | Leon, Aylin",
            "Di 11:00 Factory Ops | Leon, Theo",
            "Di 14:00 Eskalations-Check | Aylin",
            "Mi 10:00 Dealer KPI Review | Leon, Theo",
            "Mi 15:30 Rollout Sync | Aylin, Leon",
            "Do 09:00 Dealer Enablement | Aylin, Leon, Theo",
            "Do 14:30 Wochensync | Theo",
            "Fr 11:00 Forecast | Leon, Aylin",
        ],
        "notes": ["Need stronger drill-down by plant and dealer region."],
        "team_members": ["Sales: Leon", "CSM: Aylin", "Solutions: Theo"],
        "personas": ["After-Sales Manager", "Dealer Ops Lead"],
        "newsfeed": ["New dealer program approved for phased onboarding in Q4."],
        "recent_events": [
            "Heute 10:55: Escalation Matrix mit Team geteilt.",
            "Gestern: Dealer KPI Alerts kalibriert.",
            "Montag: Rollout Scope final unterschrieben.",
        ],
        "portfolio_summary": "Sehr guter Fit für Serviceprozesse und regionale Steuerung.",
        "performance_summary": "79% beantwortete Fragen, 7 offen, 2 Termine diese Woche.",
    },
    {
        "id": "orbit-pharma",
        "name": "Orbit Pharma",
        "segment": "Pharma",
        "last_visited": "Gestern",
        "is_favorite": False,
        "assigned_roles": ["admin", "analyst"],
        "owner": "V. Kirsch",
        "open_questions": 10,
        "completed_questions": 19,
        "pending_meetings": 4,
        "completed_meetings": 9,
        "documents": ["Regulatory Snapshot.pdf", "Clinical Coordination Notes.docx", "Safety Loop Checklist.md"],
        "hypotheses": [
            {
                "text": "Scope-basierte Zusammenfassungen verbessern Board Readiness für Clinical Ops.",
                "status": "unconfirmed",
            },
            {"text": "Dokumenten-Routing mit Rollenfiltern reduziert Review-Latenz.", "status": "pending"},
        ],
        "appointments": [
            "W-1 Mo 08:45 Safety Recap | Iris, Tom",
            "W-1 Di 10:00 Compliance Retro | Lara, Ben",
            "W-1 Do 14:00 Clinical Review | Iris, Tom, Lara",
            "W-1 Fr 11:00 Sprint Abschluss | Lara, Ben",
            "Mo 08:45 Daily Standup | Iris, Tom, Lara",
            "Mo 10:30 Compliance Board | Iris, Lara",
            "Mo 14:00 Risk Review | Lara, Ben",
            "Mo 16:00 EOD Sync | Iris",
            "Di 09:00 Regulatory Prep | Lara, Tom",
            "Di 11:00 Safety Loop Review | Ben, Iris",
            "Di 14:30 Clinical Alignment | Tom, Lara, Iris",
            "Di 16:30 Data Quality Check | Ben",
            "Mi 09:30 Cross-Regional Board | Iris, Tom, Lara",
            "Mi 11:30 Approval Workflow | Lara, Ben",
            "Mi 14:00 Clinical Review | Tom, Iris, Ben",
            "Mi 16:00 Phase Gate Check | Lara",
            "Do 08:30 Morning Huddle | Iris, Tom",
            "Do 10:00 Documentation Review | Ben, Lara",
            "Do 13:00 Portfolio Steering | Iris, Tom, Lara",
            "Do 15:30 Partner Sync | Iris",
            "Fr 09:00 Weekly Retrospective | Iris, Tom, Lara, Ben",
            "Fr 11:30 Steering | Lara, Tom, Iris",
            "Fr 14:00 Governance Sign-off | Lara, Ben",
            "W+1 Mo 09:00 Regulatory Planning | Lara, Tom",
            "W+1 Di 11:00 Safety Board | Iris, Ben",
            "W+1 Mi 14:00 Phase Gate Review | Lara, Iris",
            "W+1 Do 09:30 Partner Update | Tom",
            "W+1 Fr 10:00 Weekly Retrospective | Iris, Tom, Lara, Ben",
            "W+2 Mo 09:30 Q2 Clinical Planning | Iris, Tom, Lara",
            "W+2 Mi 14:00 Audit-Vorbereitung | Ben, Lara",
            "W+2 Fr 11:30 Monats-Retro | Iris, Tom",
        ],
        "notes": ["Escalation notes should include confidence level for each recommendation."],
        "team_members": ["Analyst: Iris", "Medical Ops: Tom", "Compliance: Lara", "Security: Ben"],
        "personas": ["Clinical Ops", "Regulatory Lead", "Program Manager"],
        "newsfeed": ["Regulatory team approved next-phase process harmonization across regions."],
        "recent_events": [
            "Heute 08:10: Safety Loop Checklist aktualisiert.",
            "Gestern: Clinical Board Feedback aufgenommen.",
            "Dienstag: Governance Alignment abgeschlossen.",
        ],
        "portfolio_summary": "Hoher strategischer Wert, starke Governance-Abhängigkeit.",
        "performance_summary": "66% beantwortete Fragen, 19 offen, 4 Meetings in Vorbereitung.",
    },
    {
        "id": "bluebay-hospitality",
        "name": "Bluebay Hospitality",
        "segment": "Hospitality",
        "last_visited": "11:02",
        "is_favorite": False,
        "assigned_roles": ["admin", "customer", "salesConsultant"],
        "owner": "N. Kruger",
        "open_questions": 4,
        "completed_questions": 20,
        "pending_meetings": 1,
        "completed_meetings": 6,
        "documents": ["Guest Journey Board.pdf", "Regional Playbook.md", "VIP Escalation Rules.json"],
        "hypotheses": [
            {
                "text": "Kurze Notes mit Dateianhang verbessern schichtübergreifende Übergaben.",
                "status": "pending",
            },
        ],
        "appointments": [
            "Mo 09:00 Morning Briefing | Nora, Elias, Mina",
            "Mo 11:00 VIP Case Review | Nora, Mina",
            "Mo 14:30 Partner Onboarding | Elias",
            "Di 09:30 Shift Handover | Mina, Elias",
            "Di 11:00 Guest Journey Workshop | Nora, Mina",
            "Di 15:00 Route Policy Review | Elias, Nora",
            "Mi 10:00 Regional Ops Prep | Nora, Elias",
            "Mi 13:00 Escalation Drill | Mina, Elias, Nora",
            "Do 09:00 Weekly Standup | Nora, Elias, Mina",
            "Do 11:30 Playbook Update | Mina",
            "Do 13:00 Regional Ops Sync | Nora, Elias, Mina",
            "Do 15:00 Guest Feedback Loop | Nora",
            "Fr 09:30 Weekly Wrap | Nora, Elias, Mina",
            "Fr 11:00 SLA Checkpoint | Elias, Mina",
            "Fr 14:00 Dashboard Review | Nora",
        ],
        "notes": ["Night shift requests a separate dashboard for unresolved VIP cases."],
        "team_members": ["Sales: Nora", "CSM: Elias", "Ops: Mina"],
        "personas": ["Guest Experience Lead", "Regional Operations"],
        "newsfeed": ["Three premium locations moved to the new routing policy."],
        "recent_events": [
            "Heute 10:35: VIP Rules abgestimmt.",
            "Gestern: Regional Playbook überarbeitet.",
            "Montag: Guest Journey Board erweitert.",
        ],
        "portfolio_summary": "Stabile Nutzung, hohes Potenzial bei Team-Orchestrierung.",
        "performance_summary": "84% beantwortete Fragen, 5 offen, 1 geplanter Termin.",
    },
]

PERSONAL_COLLEAGUES: list[dict] = [
    {"id": "colleague-sophie", "function_name": "Product Manager", "full_name": "Sophie Reiter"},
    {"id": "colleague-markus", "function_name": "Engineering Lead", "full_name": "Markus Haas"},
    {"id": "colleague-jana", "function_name": "UX Designer", "full_name": "Jana Wolff"},
    {"id": "colleague-tobias", "function_name": "Sales Manager", "full_name": "Tobias Kramer"},
    {"id": "colleague-miriam", "function_name": "Customer Success", "full_name": "Miriam Schulte"},
]

PERSONAL_APPOINTMENTS: list[dict] = [
    {
        "id": "personal-001",
        "day_index": 0,
        "week_index": 0,
        "time_label": "08:30",
        "end_time_label": "09:00",
        "title": "Daily Standup",
        "attendees": ["Sophie Reiter", "Markus Haas", "Jana Wolff"],
        "recurring": True,
    },
    {
        "id": "personal-002",
        "day_index": 1,
        "week_index": 0,
        "time_label": "11:00",
        "end_time_label": "12:00",
        "title": "Sprint Review",
        "attendees": ["Sophie Reiter", "Jana Wolff", "Tobias Kramer"],
        "description": "Vorstellung der Ergebnisse aus Sprint 24.",
    },
    {
        "id": "personal-003",
        "day_index": 3,
        "week_index": 0,
        "time_label": "14:00",
        "end_time_label": "14:30",
        "title": "1:1 mit Sophie",
        "attendees": ["Sophie Reiter"],
        "recurring": True,
    },
    {
        "id": "personal-004",
        "day_index": 4,
        "week_index": 0,
        "time_label": "09:30",
        "end_time_label": "10:00",
        "title": "Weekly Retrospektive",
        "attendees": ["Sophie Reiter", "Markus Haas", "Jana Wolff", "Miriam Schulte"],
        "recurring": True,
    },
    {
        "id": "personal-invite-001",
        "day_index": 1,
        "week_index": 0,
        "time_label": "15:00",
        "end_time_label": "16:00",
        "title": "Roadmap Alignment Q3",
        "attendees": ["Tobias Kramer", "Miriam Schulte", "Dominic Bechtold"],
        "description": "Abstimmung der Roadmap-Prioritäten für Q3. Deine Einschätzung zu Feature X wäre hilfreich.",
        "invited_by": "Tobias Kramer",
        "rsvp": "pending",
    },
    {
        "id": "personal-invite-002",
        "day_index": 2,
        "week_index": 0,
        "time_label": "10:00",
        "end_time_label": "10:30",
        "title": "Design Review: Onboarding Flow",
        "attendees": ["Jana Wolff", "Dominic Bechtold"],
        "description": "Jana möchte Feedback zum überarbeiteten Onboarding-Screen.",
        "invited_by": "Jana Wolff",
        "rsvp": "pending",
    },
    {
        "id": "personal-invite-003",
        "day_index": 3,
        "week_index": 0,
        "time_label": "16:00",
        "end_time_label": "17:00",
        "title": "Tech Debt Triage",
        "attendees": ["Markus Haas", "Dominic Bechtold"],
        "description": "Priorisierung offener Tech-Debt-Tickets vor dem nächsten Sprint.",
        "invited_by": "Markus Haas",
        "rsvp": "pending",
    },
    {
        "id": "personal-invite-004",
        "day_index": 0,
        "week_index": 1,
        "time_label": "13:00",
        "end_time_label": "14:00",
        "title": "Customer Feedback Session",
        "attendees": ["Miriam Schulte", "Tobias Kramer", "Dominic Bechtold"],
        "description": "Live-Feedback-Runde mit zwei Bestandskunden. Bitte Notizen vorbereiten.",
        "invited_by": "Miriam Schulte",
        "rsvp": "pending",
    },
]


async def _seed() -> None:
    async with AsyncSessionLocal() as db:
        async with db.begin():
            await db.execute(delete(Company))
            await db.execute(delete(PersonalColleague))
            await db.execute(delete(PersonalAppointment))
            db.add_all(Company(**row) for row in COMPANIES)
            db.add_all(PersonalColleague(**row) for row in PERSONAL_COLLEAGUES)
            db.add_all(PersonalAppointment(**row) for row in PERSONAL_APPOINTMENTS)
    print(
        f"Seeded {len(COMPANIES)} companies, {len(PERSONAL_COLLEAGUES)} personal colleagues, "
        f"{len(PERSONAL_APPOINTMENTS)} personal appointments."
    )


def main() -> None:
    # Ensure the schema exists (Alembic owns it). Sync call — must run outside an event loop.
    run_migrations()
    asyncio.run(_seed())


if __name__ == "__main__":
    main()
