import type { Language } from "../../features/chat/types/chat";
import type {
  CompanyRecord,
  CompanyTab,
  DisplayRole,
  WeekdayTokenEntry,
} from "./companyWorkspace.types";

export const weekdayLabelsByLanguage: Record<Language, string[]> = {
  de: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
  en: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
};

export const weekdayTokenMap: WeekdayTokenEntry[] = [
  { index: 0, tokens: ["mo", "mon"] },
  { index: 1, tokens: ["di", "tu", "tue"] },
  { index: 2, tokens: ["mi", "we", "wed"] },
  { index: 3, tokens: ["do", "th", "thu"] },
  { index: 4, tokens: ["fr", "fri"] },
  { index: 5, tokens: ["sa", "sat"] },
  { index: 6, tokens: ["so", "su", "sun"] },
];

export const tabVisibilityByRole: Record<DisplayRole, CompanyTab[]> = {
  admin: [
    "overview",
    "portfolio",
    "performance",
    "documents",
    "hypotheses",
    "appointments",
    "notes",
    "team",
    "newsfeed",
  ],
  salesConsultant: [
    "overview",
    "portfolio",
    "performance",
    "documents",
    "hypotheses",
    "appointments",
    "notes",
    "team",
    "newsfeed",
  ],
  analyst: ["overview", "portfolio", "performance", "documents", "hypotheses", "newsfeed"],
  customer: ["overview", "portfolio", "performance", "documents", "appointments", "newsfeed"],
  guest: ["overview", "documents"],
};

export const companyRecords: CompanyRecord[] = [
  {
    id: "aurora-bank",
    name: "Aurora Bank",
    segment: "Fintech",
    lastVisited: "10:22",
    isFavorite: true,
    assignedRoles: ["admin", "salesConsultant", "analyst"],
    owner: "M. Ritter",
    openQuestions: 6,
    pendingMeetings: 2,
    documents: ["Q2 Risiko-Radar", "Roadmap API Consent", "Journey Mapping v3"],
    hypotheses: [
      "Antwortquote steigt mit persona-spezifischen Follow-ups.",
      "Dokumenten-Shortcuts reduzieren offene Tickets > 20%.",
    ],
    appointments: ["Mo 11:00 Steering", "Mi 15:30 Enablement", "Fr 09:00 Sales Review"],
    notes: [
      "Decision Maker will benchmark against two competitors.",
      "Need legal review for data retention wording.",
    ],
    teamMembers: ["Sales: Lena", "CSM: Amir", "Solution: Carla", "Legal: Jens"],
    personas: ["Head of Risk", "Ops Lead", "Data Officer"],
    newsfeed: [
      "Pilot region expanded to DACH branch network.",
      "Internal KPI target updated to response-time below 2.1s.",
    ],
    recentEvents: [
      "Heute 09:40: Follow-up Meeting geplant.",
      "Gestern: Persona Mapping aktualisiert.",
      "Montag: Dokumenten-Freigabe durch Legal.",
    ],
    portfolioSummary: "2 aktive Produkte, Upsell-Potenzial im Governance-Paket.",
    performanceSummary: "81% beantwortete Fragen, 14 offen, 2 kritische Follow-ups.",
  },
  {
    id: "nordlicht-logistics",
    name: "Nordlicht Logistics",
    segment: "Transport",
    lastVisited: "09:58",
    isFavorite: false,
    assignedRoles: ["admin", "salesConsultant"],
    owner: "D. Reimann",
    openQuestions: 3,
    pendingMeetings: 1,
    documents: ["Fleet AI Review", "SLA Delta 2026", "Renewal Negotiation Notes"],
    hypotheses: ["Dispatch-Assist Feature senkt Eskalationen in Peak-Slots."],
    appointments: ["Di 14:00 KPI Review", "Do 10:30 Renewal Prep"],
    notes: ["Customer asks for dashboard access by region managers."],
    teamMembers: ["Sales: Daria", "CSM: Faris", "Ops: Kim"],
    personas: ["Head of Dispatch", "Regional Manager"],
    newsfeed: ["Two new depots are onboarding in Q3."],
    recentEvents: [
      "Heute 08:15: SLA Delta kommentiert.",
      "Gestern: Erster Renewal-Entwurf versendet.",
      "Letzte Woche: Dispatch KPI Flag gesetzt.",
    ],
    portfolioSummary: "Starke Nutzung im Dispatch, Dokumentenmodul noch gering.",
    performanceSummary: "74% beantwortete Fragen, 6 offen, 1 Termin in Vorbereitung.",
  },
  {
    id: "cobalt-health",
    name: "Cobalt Health",
    segment: "Healthcare",
    lastVisited: "Gestern",
    isFavorite: true,
    assignedRoles: ["admin", "analyst"],
    owner: "S. Nguyen",
    openQuestions: 9,
    pendingMeetings: 3,
    documents: ["Compliance Snapshot", "Patient Journey Mapping", "Insights Q1"],
    hypotheses: [
      "Mehr Kontextfelder verbessern Relevanz für Medical Persona.",
      "Weekly Summary mit offenen Themen reduziert Churn-Risiko.",
    ],
    appointments: ["Mo 08:30 Compliance Sync", "Do 16:00 Product Board"],
    notes: ["Need role-based masking for sensitive patient hints."],
    teamMembers: ["Analyst: Sina", "CSM: Daniel", "Security: Lea"],
    personas: ["Medical Ops", "Compliance Lead", "Support Manager"],
    newsfeed: ["New procurement framework approved for EMEA rollout."],
    recentEvents: [
      "Heute 07:50: Compliance Notiz aktualisiert.",
      "Gestern: Risiko-Hypothese bestätigt.",
      "Montag: Review mit Security Team.",
    ],
    portfolioSummary: "Hoher Value im Analysebereich, Pilot für Team-Workflow geplant.",
    performanceSummary: "69% beantwortete Fragen, 18 offen, 3 Termine kommende Woche.",
  },
  {
    id: "greenforge-energy",
    name: "Greenforge Energy",
    segment: "Energy",
    lastVisited: "Gestern",
    isFavorite: false,
    assignedRoles: ["admin", "customer"],
    owner: "R. Novak",
    openQuestions: 2,
    pendingMeetings: 1,
    documents: ["Grid Overview", "Portfolio Fit", "Executive Summary"],
    hypotheses: ["Automation bundle should be placed in next offer."],
    appointments: ["Fr 13:00 Site Review"],
    notes: ["Customer account sees only own entities by default."],
    teamMembers: ["Customer Admin: R. Novak", "Advisor: Mira"],
    personas: ["Plant Manager", "Finance Lead"],
    newsfeed: ["Leadership announced modernization budget for 2026."],
    recentEvents: [
      "Gestern: Site Review vorbereitet.",
      "Montag: Product fit Dokument abgelegt.",
      "Letzte Woche: Meeting Slot abgestimmt.",
    ],
    portfolioSummary: "Single-account visibility, moderate upsell readiness.",
    performanceSummary: "88% beantwortete Fragen, 3 offen, stabiler Health-Score.",
  },
  {
    id: "sunset-insurance",
    name: "Sunset Insurance",
    segment: "Insurance",
    lastVisited: "11:36",
    isFavorite: true,
    assignedRoles: ["admin", "salesConsultant", "analyst"],
    owner: "P. Kramer",
    openQuestions: 5,
    pendingMeetings: 2,
    documents: ["Claims Overview", "Renewal Draft", "Risk Signals Q2"],
    hypotheses: [
      "Persona snippets in claims context improve resolution speed.",
      "Compact weekly summary lowers escalation volume.",
    ],
    appointments: ["Di 09:30 Claims Sync", "Do 14:00 Renewal Board"],
    notes: ["Prefers short summaries and explicit risk tags."],
    teamMembers: ["Sales: Jo", "CSM: Mel", "Analyst: Tim"],
    personas: ["Claims Lead", "Operations Manager", "IT Security"],
    newsfeed: ["Board approved pilot for automated document routing."],
    recentEvents: [
      "Heute 10:10: Review-Notiz hinzugefügt.",
      "Gestern: Renewal Draft abgestimmt.",
      "Montag: KPI-Alert geschlossen.",
    ],
    portfolioSummary: "Starker Fit im Claims-Workflow, Upsell im Reporting möglich.",
    performanceSummary: "77% beantwortete Fragen, 9 offen, 2 priorisierte Meetings.",
  },
  {
    id: "nova-commerce",
    name: "Nova Commerce",
    segment: "Retail",
    lastVisited: "Heute",
    isFavorite: false,
    assignedRoles: ["admin", "salesConsultant", "customer"],
    owner: "L. Ortmann",
    openQuestions: 4,
    pendingMeetings: 1,
    documents: ["Store Rollout Plan", "Support SOP", "Executive Notes"],
    hypotheses: ["Store-level prompts can reduce ticket handovers by 18%."],
    appointments: ["Mi 13:00 Weekly Ops"],
    notes: ["Needs region-level visibility for store managers."],
    teamMembers: ["Sales: Nia", "CSM: Olek", "Ops: Rene"],
    personas: ["Retail Ops", "Regional Lead"],
    newsfeed: ["Five new stores scheduled for pilot onboarding."],
    recentEvents: [
      "Heute 09:05: Store KPI export geteilt.",
      "Gestern: SOP finalisiert.",
      "Letzte Woche: Pilot-Scope erweitert.",
    ],
    portfolioSummary: "Gute Nutzung im Tagesbetrieb, Potenzial bei Team-Modulen.",
    performanceSummary: "83% beantwortete Fragen, 5 offen, stabiler Rollout.",
  },
  {
    id: "polaris-media",
    name: "Polaris Media",
    segment: "Media",
    lastVisited: "08:42",
    isFavorite: false,
    assignedRoles: ["admin", "salesConsultant"],
    owner: "A. Weber",
    openQuestions: 7,
    pendingMeetings: 2,
    documents: ["Campaign Brief", "Persona Cluster", "Q3 Theme Map"],
    hypotheses: [
      "Persona-driven briefing templates increase response precision.",
      "Faster tagging lowers content QA loops.",
    ],
    appointments: ["Mo 16:00 Editorial", "Fr 10:00 Stakeholder Sync"],
    notes: ["Wants explicit confidence hints in recommendations."],
    teamMembers: ["Sales: Pia", "CSM: Andre", "Creative: Kim"],
    personas: ["Editorial Lead", "Campaign Owner"],
    newsfeed: ["Editorial board approved Q3 experimentation budget."],
    recentEvents: [
      "Heute 08:00: Theme Map aktualisiert.",
      "Gestern: Campaign Brief kommentiert.",
      "Dienstag: Persona Cluster erweitert.",
    ],
    portfolioSummary: "Hohe Aktivität im Kampagnenbereich, Reporting noch ausbaufähig.",
    performanceSummary: "71% beantwortete Fragen, 11 offen, 2 Fokus-Meetings.",
  },
  {
    id: "urban-harbor",
    name: "Urban Harbor",
    segment: "Real Estate",
    lastVisited: "12:11",
    isFavorite: true,
    assignedRoles: ["admin", "customer", "analyst"],
    owner: "C. Sahin",
    openQuestions: 3,
    pendingMeetings: 1,
    documents: ["Tenant Insights", "Portfolio Mix", "Risk Brief"],
    hypotheses: ["Weekly open-item digest improves board readiness."],
    appointments: ["Do 11:00 Portfolio Review"],
    notes: ["Customer team requests cleaner handover templates."],
    teamMembers: ["Customer Admin: C. Sahin", "Analyst: Noor"],
    personas: ["Portfolio Manager", "Finance Controller"],
    newsfeed: ["Two properties moved into modernization planning."],
    recentEvents: [
      "Heute 11:20: Risk Brief überarbeitet.",
      "Gestern: Tenant Insights geteilt.",
      "Montag: Portfolio Mix finalisiert.",
    ],
    portfolioSummary: "Stark in Portfolio-Transparenz, mittleres Upsell-Potenzial.",
    performanceSummary: "86% beantwortete Fragen, 4 offen, 1 Termin geplant.",
  },
  {
    id: "lumen-telecom",
    name: "Lumen Telecom",
    segment: "Telecom",
    lastVisited: "13:08",
    isFavorite: false,
    assignedRoles: ["admin", "salesConsultant", "analyst"],
    owner: "Y. Baum",
    openQuestions: 8,
    pendingMeetings: 3,
    documents: ["SLA Heatmap Q2.pdf", "Incident Playbook.md", "KPI Board v4.xlsx"],
    hypotheses: [
      "Automatisierte Priorisierung reduziert MTTD in enterprise queues.",
      "Scope-basierte KPI-Slices steigern Cross-Functional Alignment.",
    ],
    appointments: ["Mo 10:30 Ops Board", "Mi 12:00 Enterprise SLA Sync", "Fr 15:00 Exec Debrief"],
    notes: ["Need confidence gates for automated escalation suggestions."],
    teamMembers: ["Sales: Arda", "CSM: Mia", "Ops Lead: Florian", "Security: Dani"],
    personas: ["Network Ops Lead", "Enterprise CSM", "Support Director"],
    newsfeed: ["Regional NOC introduced stricter incident classification in all clusters."],
    recentEvents: [
      "Heute 12:20: KPI Board um SLA Risk Layer erweitert.",
      "Gestern: Incident Playbook finalisiert.",
      "Dienstag: Scope-Review mit Ops und Security.",
    ],
    portfolioSummary: "Breites Rollout-Potenzial, hoher Bedarf an SLA-Transparenz.",
    performanceSummary: "72% beantwortete Fragen, 13 offen, 3 priorisierte Termine.",
  },
  {
    id: "atlas-automotive",
    name: "Atlas Automotive",
    segment: "Automotive",
    lastVisited: "14:16",
    isFavorite: true,
    assignedRoles: ["admin", "customer", "salesConsultant"],
    owner: "J. Haller",
    openQuestions: 5,
    pendingMeetings: 2,
    documents: ["After-Sales Intelligence.pdf", "Factory Rollout Plan.pptx", "Escalation Matrix.csv"],
    hypotheses: ["Persona-spezifische Serviceantworten senken Rework in Dealer-Teams."],
    appointments: ["Di 11:00 Factory Ops", "Do 09:00 Dealer Enablement"],
    notes: ["Need stronger drill-down by plant and dealer region."],
    teamMembers: ["Sales: Leon", "CSM: Aylin", "Solutions: Theo"],
    personas: ["After-Sales Manager", "Dealer Ops Lead"],
    newsfeed: ["New dealer program approved for phased onboarding in Q4."],
    recentEvents: [
      "Heute 10:55: Escalation Matrix mit Team geteilt.",
      "Gestern: Dealer KPI Alerts kalibriert.",
      "Montag: Rollout Scope final unterschrieben.",
    ],
    portfolioSummary: "Sehr guter Fit für Serviceprozesse und regionale Steuerung.",
    performanceSummary: "79% beantwortete Fragen, 7 offen, 2 Termine diese Woche.",
  },
  {
    id: "orbit-pharma",
    name: "Orbit Pharma",
    segment: "Pharma",
    lastVisited: "Gestern",
    isFavorite: false,
    assignedRoles: ["admin", "analyst"],
    owner: "V. Kirsch",
    openQuestions: 10,
    pendingMeetings: 4,
    documents: ["Regulatory Snapshot.pdf", "Clinical Coordination Notes.docx", "Safety Loop Checklist.md"],
    hypotheses: [
      "Scope-basierte Zusammenfassungen verbessern Board Readiness für Clinical Ops.",
      "Dokumenten-Routing mit Rollenfiltern reduziert Review-Latenz.",
    ],
    appointments: ["Mo 09:00 Compliance Board", "Mi 17:00 Clinical Review", "Fr 11:30 Steering"],
    notes: ["Escalation notes should include confidence level for each recommendation."],
    teamMembers: ["Analyst: Iris", "Medical Ops: Tom", "Compliance: Lara", "Security: Ben"],
    personas: ["Clinical Ops", "Regulatory Lead", "Program Manager"],
    newsfeed: ["Regulatory team approved next-phase process harmonization across regions."],
    recentEvents: [
      "Heute 08:10: Safety Loop Checklist aktualisiert.",
      "Gestern: Clinical Board Feedback aufgenommen.",
      "Dienstag: Governance Alignment abgeschlossen.",
    ],
    portfolioSummary: "Hoher strategischer Wert, starke Governance-Abhängigkeit.",
    performanceSummary: "66% beantwortete Fragen, 19 offen, 4 Meetings in Vorbereitung.",
  },
  {
    id: "bluebay-hospitality",
    name: "Bluebay Hospitality",
    segment: "Hospitality",
    lastVisited: "11:02",
    isFavorite: false,
    assignedRoles: ["admin", "customer", "salesConsultant"],
    owner: "N. Kruger",
    openQuestions: 4,
    pendingMeetings: 1,
    documents: ["Guest Journey Board.pdf", "Regional Playbook.md", "VIP Escalation Rules.json"],
    hypotheses: ["Kurze Notes mit Dateianhang verbessern schichtübergreifende Übergaben."],
    appointments: ["Do 13:00 Regional Ops Sync"],
    notes: ["Night shift requests a separate dashboard for unresolved VIP cases."],
    teamMembers: ["Sales: Nora", "CSM: Elias", "Ops: Mina"],
    personas: ["Guest Experience Lead", "Regional Operations"],
    newsfeed: ["Three premium locations moved to the new routing policy."],
    recentEvents: [
      "Heute 10:35: VIP Rules abgestimmt.",
      "Gestern: Regional Playbook überarbeitet.",
      "Montag: Guest Journey Board erweitert.",
    ],
    portfolioSummary: "Stabile Nutzung, hohes Potenzial bei Team-Orchestrierung.",
    performanceSummary: "84% beantwortete Fragen, 5 offen, 1 geplanter Termin.",
  },
];
