import type { Language } from "../../features/chat/types/chat";
import type {
  CompanyRecord,
  CompanyTab,
  CompanyTeamMemberEntry,
  DisplayRole,
  HypothesisEntry,
  ParsedAppointmentItem,
  WeekdayTokenEntry,
} from "./companyWorkspace.types";

export const weekdayLabelsByLanguage: Record<Language, string[]> = {
  de: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
  en: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
};

export const weekdayTokenMap: WeekdayTokenEntry[] = [
  { index: 0, tokens: ["mo", "mon"] },
  { index: 1, tokens: ["di", "tu", "tue"] },
  { index: 2, tokens: ["mi", "we", "wed"] },
  { index: 3, tokens: ["do", "th", "thu"] },
  { index: 4, tokens: ["fr", "fri"] },
  { index: 5, tokens: ["sa", "sat"] },
  { index: 6, tokens: ["so", "su", "sun"] },
];

export const tabVisibilityByRole: Record<DisplayRole, CompanyTab[]> = {
  admin: [
    "overview",
    "portfolio",
    "performance",
    "documents",
    "hypotheses",
    "appointments",
    "notes",
    "team",
    "newsfeed",
  ],
  salesConsultant: [
    "overview",
    "portfolio",
    "performance",
    "documents",
    "hypotheses",
    "appointments",
    "notes",
    "team",
    "newsfeed",
  ],
  analyst: ["overview", "portfolio", "performance", "documents", "hypotheses", "newsfeed"],
  customer: ["overview", "portfolio", "performance", "documents", "appointments", "newsfeed"],
  guest: ["overview", "documents"],
};

export const companyRecords: CompanyRecord[] = [
  {
    id: "aurora-bank",
    name: "Aurora Bank",
    segment: "Fintech",
    lastVisited: "10:22",
    isFavorite: true,
    assignedRoles: ["admin", "salesConsultant", "analyst"],
    owner: "M. Ritter",
    openQuestions: 6,
    completedQuestions: 26,
    pendingMeetings: 2,
    completedMeetings: 9,
    documents: ["Q2 Risiko-Radar", "Roadmap API Consent", "Journey Mapping v3"],
    hypotheses: [
      { text: "Antwortquote steigt mit persona-spezifischen Follow-ups.", status: "confirmed" },
      { text: "Dokumenten-Shortcuts reduzieren offene Tickets > 20%.", status: "confirmed" },
    ] satisfies HypothesisEntry[],
    appointments: [
      // ── W-1 (last week) ──────────────────────────────────────────────────
      "W-1 Mo 09:00 Sprint Review | Lena, Amir, Dominic",
      "W-1 Mo 14:30 Kunden-Präsentation | Carla, Jens",
      "W-1 Di 10:00 Technische Abstimmung | Amir, Carla",
      "W-1 Mi 09:30 Journey Workshop | Lena, Carla, Dominic",
      "W-1 Do 15:00 Risiko-Retrospektive | Jens, Amir",
      "W-1 Fr 11:00 Sprint Abschluss | Lena, Amir, Dominic",
      // ── W0 (current week) ────────────────────────────────────────────────
      "Mo 08:30-09:00 Daily Standup | Lena, Amir, Dominic",
      "Mo 10:00-11:30 Risk Review | Amir, Jens",
      "Mo 11:00-12:00 Steering | Lena, Amir, Jens",
      "Mo 14:00-15:00 Demo Prep | Carla, Lena",
      "Mo 16:30-17:00 EOD Sync | Amir",
      "Di 09:00-10:30 QBR Vorbereitung | Jens, Carla, Dominic",
      "Di 10:30-11:30 Legal Abstimmung | Jens",
      "Di 13:00-14:00 Produkt-Feedback | Lena, Amir, Carla",
      "Di 15:00-15:30 Client Check-in | Carla",
      "Di 17:00-18:00 Release Planning | Amir, Carla",
      "Mi 08:30-09:00 Daily Standup | Lena, Amir",
      "Mi 09:30-11:30 Roadmap Session | Carla, Jens, Lena, Dominic",
      "Mi 11:30-12:30 API Workshop | Amir",
      "Mi 15:30-16:30 Enablement | Carla, Lena",
      "Mi 16:00-17:00 Budget Review | Jens",
      "Do 09:00-10:30 Strategy Review | Lena, Amir, Jens, Dominic",
      "Do 10:30-11:30 Einwand-Handling | Carla, Lena",
      "Do 14:00-15:00 Risk Assessment | Jens",
      "Do 15:30-16:00 Next Steps | Amir",
      "Fr 09:00-10:00 Sales Review | Amir, Carla, Jens, Dominic",
      "Fr 10:30-11:30 Weekly Close | Lena, Amir",
      "Fr 13:00-14:30 Retro | Carla, Jens",
      "Fr 15:00-16:00 Forecast | Amir, Lena",
      // ── W+1 (next week) ──────────────────────────────────────────────────
      "W+1 Mo 08:30 Sprint Planning | Lena, Amir, Dominic",
      "W+1 Mo 10:00 Risk Monitoring | Amir, Jens",
      "W+1 Di 09:30 Produkt-Roadmap | Carla, Lena",
      "W+1 Di 14:00 Legal Update | Jens, Dominic",
      "W+1 Mi 11:00 Data Review | Amir, Carla",
      "W+1 Mi 14:30 API Consent Sync | Lena, Jens",
      "W+1 Do 10:00 Quarterly Check-in | Lena, Amir, Carla, Jens, Dominic",
      "W+1 Do 15:30 Eskalations-Check | Amir",
      "W+1 Fr 10:00 Weekly Wrap | Amir, Lena",
      "W+1 Fr 13:00 Forecast Prep | Carla, Jens",
      // ── W+2 (week after next) ─────────────────────────────────────────────
      "W+2 Mo 09:00 OKR Review | Lena, Amir, Dominic",
      "W+2 Mo 14:00 Governance Session | Jens",
      "W+2 Di 11:00 Security Audit | Jens, Amir",
      "W+2 Mi 10:30 Feature Preview | Carla, Lena, Dominic",
      "W+2 Mi 14:00 Architecture Review | Amir, Carla",
      "W+2 Do 10:00 Stakeholder-Sync | Jens",
      "W+2 Do 14:30 Release Gate | Lena, Amir, Carla",
      "W+2 Fr 12:00 Monats-Abschluss | Amir, Carla, Dominic",
    ],
    notes: [
      "Decision Maker will benchmark against two competitors.",
      "Need legal review for data retention wording.",
    ],
    teamMembers: ["Sales: Lena", "CSM: Amir", "Solution: Carla", "Legal: Jens"],
    personas: ["Head of Risk", "Ops Lead", "Data Officer"],
    newsfeed: [
      "Pilot region expanded to DACH branch network.",
      "Internal KPI target updated to response-time below 2.1s.",
    ],
    recentEvents: [
      "Heute 09:40: Follow-up Meeting geplant.",
      "Gestern: Persona Mapping aktualisiert.",
      "Montag: Dokumenten-Freigabe durch Legal.",
    ],
    portfolioSummary: "2 aktive Produkte, Upsell-Potenzial im Governance-Paket.",
    performanceSummary: "81% beantwortete Fragen, 14 offen, 2 kritische Follow-ups.",
  },
  {
    id: "nordlicht-logistics",
    name: "Nordlicht Logistics",
    segment: "Transport",
    lastVisited: "09:58",
    isFavorite: false,
    assignedRoles: ["admin", "salesConsultant"],
    owner: "D. Reimann",
    openQuestions: 3,
    completedQuestions: 14,
    pendingMeetings: 1,
    completedMeetings: 5,
    documents: ["Fleet AI Review", "SLA Delta 2026", "Renewal Negotiation Notes"],
    hypotheses: [
      { text: "Dispatch-Assist Feature senkt Eskalationen in Peak-Slots.", status: "pending" },
    ] satisfies HypothesisEntry[],
    appointments: [
      // ── W-1 (last week) ──────────────────────────────────────────────────
      "W-1 Mo 10:00 Fleet Recap | Daria, Kim",
      "W-1 Di 14:30 SLA Analyse | Faris, Dominic",
      "W-1 Do 09:00 Eskalations-Log | Daria, Kim, Faris",
      "W-1 Fr 11:00 Sprint Review | Kim, Dominic",
      // ── W0 (current week) ────────────────────────────────────────────────
      "Mo 09:00-09:30 Fleet-Status | Daria, Kim, Dominic",
      "Di 10:30-12:00 SLA-Abstimmung | Kim, Faris",
      "Di 14:00-15:00 KPI Review | Daria, Faris, Dominic",
      "Mi 11:00-11:30 Eskalations-Check | Faris",
      "Mi 14:30-15:30 Ops-Sync | Kim, Dominic",
      "Do 09:30-11:00 Renewal Prep | Daria, Kim, Faris",
      "Do 15:00-15:30 Wochenbericht | Daria, Faris, Dominic",
      "Fr 09:30-10:00 Fleet Close | Kim",
      // ── W+1 (next week) ──────────────────────────────────────────────────
      "W+1 Mo 09:30 Route Planning | Daria, Kim",
      "W+1 Di 11:00 Renewal Final | Faris, Daria, Dominic",
      "W+1 Mi 10:00 Ops-Update | Kim",
      "W+1 Mi 15:00 Dispatch Review | Daria, Faris",
      "W+1 Do 14:00 KPI Board | Daria, Faris",
      "W+1 Fr 10:30 Wochensync | Kim, Faris, Dominic",
      // ── W+2 (week after next) ─────────────────────────────────────────────
      "W+2 Mo 09:00 Q2 Kick-off | Daria, Kim, Faris",
      "W+2 Mi 11:00 Forecast | Faris, Dominic",
      "W+2 Do 14:00 SLA Board | Daria, Kim",
      "W+2 Fr 09:00 Abschluss-Meeting | Daria",
    ],
    notes: ["Customer asks for dashboard access by region managers."],
    teamMembers: ["Sales: Daria", "CSM: Faris", "Ops: Kim"],
    personas: ["Head of Dispatch", "Regional Manager"],
    newsfeed: ["Two new depots are onboarding in Q3."],
    recentEvents: [
      "Heute 08:15: SLA Delta kommentiert.",
      "Gestern: Erster Renewal-Entwurf versendet.",
      "Letzte Woche: Dispatch KPI Flag gesetzt.",
    ],
    portfolioSummary: "Starke Nutzung im Dispatch, Dokumentenmodul noch gering.",
    performanceSummary: "74% beantwortete Fragen, 6 offen, 1 Termin in Vorbereitung.",
  },
  {
    id: "cobalt-health",
    name: "Cobalt Health",
    segment: "Healthcare",
    lastVisited: "Gestern",
    isFavorite: true,
    assignedRoles: ["admin", "analyst"],
    owner: "S. Nguyen",
    openQuestions: 9,
    completedQuestions: 21,
    pendingMeetings: 3,
    completedMeetings: 7,
    documents: ["Compliance Snapshot", "Patient Journey Mapping", "Insights Q1"],
    hypotheses: [
      { text: "Mehr Kontextfelder verbessern Relevanz für Medical Persona.", status: "confirmed" },
      { text: "Weekly Summary mit offenen Themen reduziert Churn-Risiko.", status: "unconfirmed" },
    ] satisfies HypothesisEntry[],
    appointments: [
      // ── W-1 ──────────────────────────────────────────────────────────────
      "W-1 Mo 09:00 Compliance Review | Sina, Lea",
      "W-1 Mi 10:30 Patientendaten-Audit | Daniel, Lea",
      "W-1 Do 14:00 Security Sync | Lea",
      "W-1 Fr 11:00 Wochensync | Sina, Daniel",
      // ── W0 ───────────────────────────────────────────────────────────────
      "Mo 08:30 Compliance Sync | Sina, Lea",
      "Mo 10:00 Patient Journey Review | Daniel, Sina",
      "Di 09:00 Datenschutz-Check | Lea",
      "Di 14:00 Product Update | Sina, Daniel",
      "Mi 11:00 Risiko-Assessment | Sina, Lea",
      "Mi 15:00 Insights Deep Dive | Daniel",
      "Do 09:30 IT-Security Review | Lea, Daniel",
      "Do 16:00 Product Board | Daniel, Sina, Lea",
      "Fr 10:00 Wochensync | Sina, Daniel",
      // ── W+1 ──────────────────────────────────────────────────────────────
      "W+1 Mo 08:30 Datenschutz-Sprint | Sina, Lea",
      "W+1 Di 10:00 Produkt-Check | Daniel, Sina",
      "W+1 Mi 14:00 Risiko-Review | Lea, Sina",
      "W+1 Do 09:00 Clinical Update | Daniel",
      "W+1 Fr 12:00 Monats-Abschluss | Sina, Daniel, Lea",
      // ── W+2 ──────────────────────────────────────────────────────────────
      "W+2 Mo 10:00 Strategie-Sync | Sina, Daniel",
      "W+2 Di 14:00 Audit-Vorbereitung | Lea",
      "W+2 Fr 11:30 Monats-Retro | Sina, Daniel",
    ],
    notes: ["Need role-based masking for sensitive patient hints."],
    teamMembers: ["Analyst: Sina", "CSM: Daniel", "Security: Lea"],
    personas: ["Medical Ops", "Compliance Lead", "Support Manager"],
    newsfeed: ["New procurement framework approved for EMEA rollout."],
    recentEvents: [
      "Heute 07:50: Compliance Notiz aktualisiert.",
      "Gestern: Risiko-Hypothese bestätigt.",
      "Montag: Review mit Security Team.",
    ],
    portfolioSummary: "Hoher Value im Analysebereich, Pilot für Team-Workflow geplant.",
    performanceSummary: "69% beantwortete Fragen, 18 offen, 3 Termine kommende Woche.",
  },
  {
    id: "greenforge-energy",
    name: "Greenforge Energy",
    segment: "Energy",
    lastVisited: "Gestern",
    isFavorite: false,
    assignedRoles: ["admin", "customer"],
    owner: "R. Novak",
    openQuestions: 2,
    completedQuestions: 11,
    pendingMeetings: 1,
    completedMeetings: 4,
    documents: ["Grid Overview", "Portfolio Fit", "Executive Summary"],
    hypotheses: [
      { text: "Automation bundle should be placed in next offer.", status: "pending" },
    ] satisfies HypothesisEntry[],
    appointments: [
      "Mo 09:30 Budget Sync | R. Novak, Mira",
      "Mi 11:00 Grid Overview | Mira",
      "Do 14:00 Exec Briefing | R. Novak",
      "Fr 10:00 Site Review | R. Novak, Mira",
      "Fr 13:00 Wochensync | Mira",
    ],
    notes: ["Customer account sees only own entities by default."],
    teamMembers: ["Customer Admin: R. Novak", "Advisor: Mira"],
    personas: ["Plant Manager", "Finance Lead"],
    newsfeed: ["Leadership announced modernization budget for 2026."],
    recentEvents: [
      "Gestern: Site Review vorbereitet.",
      "Montag: Product fit Dokument abgelegt.",
      "Letzte Woche: Meeting Slot abgestimmt.",
    ],
    portfolioSummary: "Single-account visibility, moderate upsell readiness.",
    performanceSummary: "88% beantwortete Fragen, 3 offen, stabiler Health-Score.",
  },
  {
    id: "sunset-insurance",
    name: "Sunset Insurance",
    segment: "Insurance",
    lastVisited: "11:36",
    isFavorite: true,
    assignedRoles: ["admin", "salesConsultant", "analyst"],
    owner: "P. Kramer",
    openQuestions: 5,
    completedQuestions: 19,
    pendingMeetings: 2,
    completedMeetings: 7,
    documents: ["Claims Overview", "Renewal Draft", "Risk Signals Q2"],
    hypotheses: [
      { text: "Persona snippets in claims context improve resolution speed.", status: "confirmed" },
      { text: "Compact weekly summary lowers escalation volume.", status: "unconfirmed" },
    ] satisfies HypothesisEntry[],
    appointments: [
      "Mo 08:45 Wochenbriefing | Jo, Mel, Tim",
      "Di 09:30 Claims Sync | Jo, Mel",
      "Di 14:30 Risk Signals Review | Tim",
      "Mi 10:00 Eskalations-Check | Jo",
      "Mi 15:00 Renewal Vorbereitung | Mel, Tim",
      "Do 09:30 Legal Abstimmung | Tim",
      "Do 14:00 Renewal Board | Tim, Jo, Mel",
      "Fr 11:00 Weekly Close | Jo, Mel",
    ],
    notes: ["Prefers short summaries and explicit risk tags."],
    teamMembers: ["Sales: Jo", "CSM: Mel", "Analyst: Tim"],
    personas: ["Claims Lead", "Operations Manager", "IT Security"],
    newsfeed: ["Board approved pilot for automated document routing."],
    recentEvents: [
      "Heute 10:10: Review-Notiz hinzugefügt.",
      "Gestern: Renewal Draft abgestimmt.",
      "Montag: KPI-Alert geschlossen.",
    ],
    portfolioSummary: "Starker Fit im Claims-Workflow, Upsell im Reporting möglich.",
    performanceSummary: "77% beantwortete Fragen, 9 offen, 2 priorisierte Meetings.",
  },
  {
    id: "nova-commerce",
    name: "Nova Commerce",
    segment: "Retail",
    lastVisited: "Heute",
    isFavorite: false,
    assignedRoles: ["admin", "salesConsultant", "customer"],
    owner: "L. Ortmann",
    openQuestions: 4,
    completedQuestions: 18,
    pendingMeetings: 1,
    completedMeetings: 5,
    documents: ["Store Rollout Plan", "Support SOP", "Executive Notes"],
    hypotheses: [
      { text: "Store-level prompts can reduce ticket handovers by 18%.", status: "confirmed" },
    ] satisfies HypothesisEntry[],
    appointments: [
      "Mo 09:00 Store Briefing | Nia, Rene",
      "Di 11:00 Ops-Sync | Olek, Rene",
      "Mi 10:30 SOP Review | Nia",
      "Mi 13:00 Weekly Ops | Nia, Olek, Rene",
      "Do 15:00 Region-Update | Olek",
      "Fr 09:30 Rollout Check | Nia, Olek",
    ],
    notes: ["Needs region-level visibility for store managers."],
    teamMembers: ["Sales: Nia", "CSM: Olek", "Ops: Rene"],
    personas: ["Retail Ops", "Regional Lead"],
    newsfeed: ["Five new stores scheduled for pilot onboarding."],
    recentEvents: [
      "Heute 09:05: Store KPI export geteilt.",
      "Gestern: SOP finalisiert.",
      "Letzte Woche: Pilot-Scope erweitert.",
    ],
    portfolioSummary: "Gute Nutzung im Tagesbetrieb, Potenzial bei Team-Modulen.",
    performanceSummary: "83% beantwortete Fragen, 5 offen, stabiler Rollout.",
  },
  {
    id: "polaris-media",
    name: "Polaris Media",
    segment: "Media",
    lastVisited: "08:42",
    isFavorite: false,
    assignedRoles: ["admin", "salesConsultant"],
    owner: "A. Weber",
    openQuestions: 7,
    completedQuestions: 17,
    pendingMeetings: 2,
    completedMeetings: 6,
    documents: ["Campaign Brief", "Persona Cluster", "Q3 Theme Map"],
    hypotheses: [
      { text: "Persona-driven briefing templates increase response precision.", status: "unconfirmed" },
      { text: "Faster tagging lowers content QA loops.", status: "pending" },
    ] satisfies HypothesisEntry[],
    appointments: [
      "Mo 09:30 Redaktions-Briefing | Kim, Andre",
      "Mo 14:00 Campaign Kick-off | Pia, Kim",
      "Mo 16:00 Editorial | Pia, Kim",
      "Di 11:00 Content Review | Kim",
      "Di 15:30 KPI-Update | Andre, Pia",
      "Mi 10:00 QA-Loop | Kim, Andre",
      "Do 09:00 Persona-Update | Pia",
      "Do 14:30 Reporting Session | Andre, Kim",
      "Fr 10:00 Stakeholder Sync | Andre, Pia, Kim",
      "Fr 13:00 Wochensync | Pia",
    ],
    notes: ["Wants explicit confidence hints in recommendations."],
    teamMembers: ["Sales: Pia", "CSM: Andre", "Creative: Kim"],
    personas: ["Editorial Lead", "Campaign Owner"],
    newsfeed: ["Editorial board approved Q3 experimentation budget."],
    recentEvents: [
      "Heute 08:00: Theme Map aktualisiert.",
      "Gestern: Campaign Brief kommentiert.",
      "Dienstag: Persona Cluster erweitert.",
    ],
    portfolioSummary: "Hohe Aktivität im Kampagnenbereich, Reporting noch ausbaufähig.",
    performanceSummary: "71% beantwortete Fragen, 11 offen, 2 Fokus-Meetings.",
  },
  {
    id: "urban-harbor",
    name: "Urban Harbor",
    segment: "Real Estate",
    lastVisited: "12:11",
    isFavorite: true,
    assignedRoles: ["admin", "customer", "analyst"],
    owner: "C. Sahin",
    openQuestions: 3,
    completedQuestions: 18,
    pendingMeetings: 1,
    completedMeetings: 6,
    documents: ["Tenant Insights", "Portfolio Mix", "Risk Brief"],
    hypotheses: [
      { text: "Weekly open-item digest improves board readiness.", status: "pending" },
    ] satisfies HypothesisEntry[],
    appointments: [
      "Mo 10:00 Risk Brief Review | Noor",
      "Di 14:00 Tenant Insights | C. Sahin, Noor",
      "Mi 09:30 Portfolio-Update | Noor",
      "Do 11:00 Portfolio Review | C. Sahin, Noor",
      "Do 15:30 Board Prep | C. Sahin",
      "Fr 10:30 Wochensync | Noor",
    ],
    notes: ["Customer team requests cleaner handover templates."],
    teamMembers: ["Customer Admin: C. Sahin", "Analyst: Noor"],
    personas: ["Portfolio Manager", "Finance Controller"],
    newsfeed: ["Two properties moved into modernization planning."],
    recentEvents: [
      "Heute 11:20: Risk Brief überarbeitet.",
      "Gestern: Tenant Insights geteilt.",
      "Montag: Portfolio Mix finalisiert.",
    ],
    portfolioSummary: "Stark in Portfolio-Transparenz, mittleres Upsell-Potenzial.",
    performanceSummary: "86% beantwortete Fragen, 4 offen, 1 Termin geplant.",
  },
  {
    id: "lumen-telecom",
    name: "Lumen Telecom",
    segment: "Telecom",
    lastVisited: "13:08",
    isFavorite: false,
    assignedRoles: ["admin", "salesConsultant", "analyst"],
    owner: "Y. Baum",
    openQuestions: 8,
    completedQuestions: 20,
    pendingMeetings: 3,
    completedMeetings: 8,
    documents: ["SLA Heatmap Q2.pdf", "Incident Playbook.md", "KPI Board v4.xlsx"],
    hypotheses: [
      { text: "Automatisierte Priorisierung reduziert MTTD in enterprise queues.", status: "confirmed" },
      { text: "Scope-basierte KPI-Slices steigern Cross-Functional Alignment.", status: "unconfirmed" },
    ] satisfies HypothesisEntry[],
    appointments: [
      // ── W-1 ──────────────────────────────────────────────────────────────
      "W-1 Mo 09:30 Incident Recap | Florian, Dani",
      "W-1 Di 11:00 SLA Analyse | Arda, Mia",
      "W-1 Do 14:30 Eskalations-Review | Florian, Dani",
      "W-1 Fr 10:00 Sprint Abschluss | Mia, Arda",
      // ── W0 ───────────────────────────────────────────────────────────────
      "Mo 08:30 Incident Debrief | Florian, Dani",
      "Mo 10:30 Ops Board | Arda, Florian",
      "Mo 14:00 SLA Forecast | Mia",
      "Di 09:00 NOC-Update | Dani, Florian",
      "Di 11:30 KPI Review | Arda, Mia",
      "Mi 10:00 Eskalationsrunde | Florian, Dani",
      "Mi 12:00 Enterprise SLA Sync | Mia, Florian, Dani",
      "Mi 15:00 Team Sync | Arda",
      "Do 09:30 Security Check | Dani",
      "Do 14:00 Cross-Functional | Arda, Mia, Florian",
      "Fr 10:00 Wochenbericht | Mia, Arda",
      "Fr 15:00 Exec Debrief | Arda, Mia, Florian",
      // ── W+1 ──────────────────────────────────────────────────────────────
      "W+1 Mo 08:30 NOC Planning | Dani, Florian",
      "W+1 Di 11:00 SLA Review | Mia, Arda",
      "W+1 Mi 09:30 Incident Playbook Update | Florian",
      "W+1 Do 14:00 Enterprise Check-in | Arda, Mia",
      "W+1 Fr 10:00 Wochenbericht | Mia, Arda",
      // ── W+2 ──────────────────────────────────────────────────────────────
      "W+2 Mo 10:00 Q2 Ops Planning | Arda, Florian",
      "W+2 Mi 14:00 KPI Board | Mia, Dani",
      "W+2 Fr 11:00 Monats-Retro | Arda, Mia, Florian",
    ],
    notes: ["Need confidence gates for automated escalation suggestions."],
    teamMembers: ["Sales: Arda", "CSM: Mia", "Ops Lead: Florian", "Security: Dani"],
    personas: ["Network Ops Lead", "Enterprise CSM", "Support Director"],
    newsfeed: ["Regional NOC introduced stricter incident classification in all clusters."],
    recentEvents: [
      "Heute 12:20: KPI Board um SLA Risk Layer erweitert.",
      "Gestern: Incident Playbook finalisiert.",
      "Dienstag: Scope-Review mit Ops und Security.",
    ],
    portfolioSummary: "Breites Rollout-Potenzial, hoher Bedarf an SLA-Transparenz.",
    performanceSummary: "72% beantwortete Fragen, 13 offen, 3 priorisierte Termine.",
  },
  {
    id: "atlas-automotive",
    name: "Atlas Automotive",
    segment: "Automotive",
    lastVisited: "14:16",
    isFavorite: true,
    assignedRoles: ["admin", "customer", "salesConsultant"],
    owner: "J. Haller",
    openQuestions: 5,
    completedQuestions: 19,
    pendingMeetings: 2,
    completedMeetings: 8,
    documents: ["After-Sales Intelligence.pdf", "Factory Rollout Plan.pptx", "Escalation Matrix.csv"],
    hypotheses: [
      { text: "Persona-spezifische Serviceantworten senken Rework in Dealer-Teams.", status: "confirmed" },
    ] satisfies HypothesisEntry[],
    appointments: [
      "Mo 09:30 Service-Briefing | Leon, Aylin",
      "Di 11:00 Factory Ops | Leon, Theo",
      "Di 14:00 Eskalations-Check | Aylin",
      "Mi 10:00 Dealer KPI Review | Leon, Theo",
      "Mi 15:30 Rollout Sync | Aylin, Leon",
      "Do 09:00 Dealer Enablement | Aylin, Leon, Theo",
      "Do 14:30 Wochensync | Theo",
      "Fr 11:00 Forecast | Leon, Aylin",
    ],
    notes: ["Need stronger drill-down by plant and dealer region."],
    teamMembers: ["Sales: Leon", "CSM: Aylin", "Solutions: Theo"],
    personas: ["After-Sales Manager", "Dealer Ops Lead"],
    newsfeed: ["New dealer program approved for phased onboarding in Q4."],
    recentEvents: [
      "Heute 10:55: Escalation Matrix mit Team geteilt.",
      "Gestern: Dealer KPI Alerts kalibriert.",
      "Montag: Rollout Scope final unterschrieben.",
    ],
    portfolioSummary: "Sehr guter Fit für Serviceprozesse und regionale Steuerung.",
    performanceSummary: "79% beantwortete Fragen, 7 offen, 2 Termine diese Woche.",
  },
  {
    id: "orbit-pharma",
    name: "Orbit Pharma",
    segment: "Pharma",
    lastVisited: "Gestern",
    isFavorite: false,
    assignedRoles: ["admin", "analyst"],
    owner: "V. Kirsch",
    openQuestions: 10,
    completedQuestions: 19,
    pendingMeetings: 4,
    completedMeetings: 9,
    documents: ["Regulatory Snapshot.pdf", "Clinical Coordination Notes.docx", "Safety Loop Checklist.md"],
    hypotheses: [
      { text: "Scope-basierte Zusammenfassungen verbessern Board Readiness für Clinical Ops.", status: "unconfirmed" },
      { text: "Dokumenten-Routing mit Rollenfiltern reduziert Review-Latenz.", status: "pending" },
    ] satisfies HypothesisEntry[],
    appointments: [
      // ── W-1 ──────────────────────────────────────────────────────────────
      "W-1 Mo 08:45 Safety Recap | Iris, Tom",
      "W-1 Di 10:00 Compliance Retro | Lara, Ben",
      "W-1 Do 14:00 Clinical Review | Iris, Tom, Lara",
      "W-1 Fr 11:00 Sprint Abschluss | Lara, Ben",
      // ── W0 ───────────────────────────────────────────────────────────────
      "Mo 08:45 Daily Standup | Iris, Tom, Lara",
      "Mo 10:30 Compliance Board | Iris, Lara",
      "Mo 14:00 Risk Review | Lara, Ben",
      "Mo 16:00 EOD Sync | Iris",
      "Di 09:00 Regulatory Prep | Lara, Tom",
      "Di 11:00 Safety Loop Review | Ben, Iris",
      "Di 14:30 Clinical Alignment | Tom, Lara, Iris",
      "Di 16:30 Data Quality Check | Ben",
      "Mi 09:30 Cross-Regional Board | Iris, Tom, Lara",
      "Mi 11:30 Approval Workflow | Lara, Ben",
      "Mi 14:00 Clinical Review | Tom, Iris, Ben",
      "Mi 16:00 Phase Gate Check | Lara",
      "Do 08:30 Morning Huddle | Iris, Tom",
      "Do 10:00 Documentation Review | Ben, Lara",
      "Do 13:00 Portfolio Steering | Iris, Tom, Lara",
      "Do 15:30 Partner Sync | Iris",
      "Fr 09:00 Weekly Retrospective | Iris, Tom, Lara, Ben",
      "Fr 11:30 Steering | Lara, Tom, Iris",
      "Fr 14:00 Governance Sign-off | Lara, Ben",
      // ── W+1 ──────────────────────────────────────────────────────────────
      "W+1 Mo 09:00 Regulatory Planning | Lara, Tom",
      "W+1 Di 11:00 Safety Board | Iris, Ben",
      "W+1 Mi 14:00 Phase Gate Review | Lara, Iris",
      "W+1 Do 09:30 Partner Update | Tom",
      "W+1 Fr 10:00 Weekly Retrospective | Iris, Tom, Lara, Ben",
      // ── W+2 ──────────────────────────────────────────────────────────────
      "W+2 Mo 09:30 Q2 Clinical Planning | Iris, Tom, Lara",
      "W+2 Mi 14:00 Audit-Vorbereitung | Ben, Lara",
      "W+2 Fr 11:30 Monats-Retro | Iris, Tom",
    ],
    notes: ["Escalation notes should include confidence level for each recommendation."],
    teamMembers: ["Analyst: Iris", "Medical Ops: Tom", "Compliance: Lara", "Security: Ben"],
    personas: ["Clinical Ops", "Regulatory Lead", "Program Manager"],
    newsfeed: ["Regulatory team approved next-phase process harmonization across regions."],
    recentEvents: [
      "Heute 08:10: Safety Loop Checklist aktualisiert.",
      "Gestern: Clinical Board Feedback aufgenommen.",
      "Dienstag: Governance Alignment abgeschlossen.",
    ],
    portfolioSummary: "Hoher strategischer Wert, starke Governance-Abhängigkeit.",
    performanceSummary: "66% beantwortete Fragen, 19 offen, 4 Meetings in Vorbereitung.",
  },
  {
    id: "bluebay-hospitality",
    name: "Bluebay Hospitality",
    segment: "Hospitality",
    lastVisited: "11:02",
    isFavorite: false,
    assignedRoles: ["admin", "customer", "salesConsultant"],
    owner: "N. Kruger",
    openQuestions: 4,
    completedQuestions: 20,
    pendingMeetings: 1,
    completedMeetings: 6,
    documents: ["Guest Journey Board.pdf", "Regional Playbook.md", "VIP Escalation Rules.json"],
    hypotheses: [
      { text: "Kurze Notes mit Dateianhang verbessern schichtübergreifende Übergaben.", status: "pending" },
    ] satisfies HypothesisEntry[],
    appointments: [
      "Mo 09:00 Morning Briefing | Nora, Elias, Mina",
      "Mo 11:00 VIP Case Review | Nora, Mina",
      "Mo 14:30 Partner Onboarding | Elias",
      "Di 09:30 Shift Handover | Mina, Elias",
      "Di 11:00 Guest Journey Workshop | Nora, Mina",
      "Di 15:00 Route Policy Review | Elias, Nora",
      "Mi 10:00 Regional Ops Prep | Nora, Elias",
      "Mi 13:00 Escalation Drill | Mina, Elias, Nora",
      "Do 09:00 Weekly Standup | Nora, Elias, Mina",
      "Do 11:30 Playbook Update | Mina",
      "Do 13:00 Regional Ops Sync | Nora, Elias, Mina",
      "Do 15:00 Guest Feedback Loop | Nora",
      "Fr 09:30 Weekly Wrap | Nora, Elias, Mina",
      "Fr 11:00 SLA Checkpoint | Elias, Mina",
      "Fr 14:00 Dashboard Review | Nora",
    ],
    notes: ["Night shift requests a separate dashboard for unresolved VIP cases."],
    teamMembers: ["Sales: Nora", "CSM: Elias", "Ops: Mina"],
    personas: ["Guest Experience Lead", "Regional Operations"],
    newsfeed: ["Three premium locations moved to the new routing policy."],
    recentEvents: [
      "Heute 10:35: VIP Rules abgestimmt.",
      "Gestern: Regional Playbook überarbeitet.",
      "Montag: Guest Journey Board erweitert.",
    ],
    portfolioSummary: "Stabile Nutzung, hohes Potenzial bei Team-Orchestrierung.",
    performanceSummary: "84% beantwortete Fragen, 5 offen, 1 geplanter Termin.",
  },
];

// ── Personal desk mock data ────────────────────────────────────────────────────

/**
 * A small fixed list of colleagues that appear in the personal calendar's
 * assignee-select and as invite senders.  These are purely simulated — no real
 * user account exists behind them.
 */
export const personalColleagues: CompanyTeamMemberEntry[] = [
  { id: "colleague-sophie",  functionName: "Product Manager",    fullName: "Sophie Reiter"   },
  { id: "colleague-markus",  functionName: "Engineering Lead",   fullName: "Markus Haas"     },
  { id: "colleague-jana",    functionName: "UX Designer",        fullName: "Jana Wolff"      },
  { id: "colleague-tobias",  functionName: "Sales Manager",      fullName: "Tobias Kramer"   },
  { id: "colleague-miriam",  functionName: "Customer Success",   fullName: "Miriam Schulte"  },
];

/**
 * Personal appointments for Dominic Bechtold (the active dev profile).
 * Entries with `invitedBy` + `rsvp: "pending"` simulate incoming meeting invites
 * that still need to be accepted or declined.
 */
export const personalAppointments: ParsedAppointmentItem[] = [
  // ── Own / already-accepted appointments (current week W0) ─────────────────
  {
    id: "personal-001",
    dayIndex: 0, // Mo
    weekIndex: 0,
    timeLabel: "08:30",
    endTimeLabel: "09:00",
    title: "Daily Standup",
    attendees: ["Sophie Reiter", "Markus Haas", "Jana Wolff"],
    recurring: true,
  },
  {
    id: "personal-002",
    dayIndex: 1, // Di
    weekIndex: 0,
    timeLabel: "11:00",
    endTimeLabel: "12:00",
    title: "Sprint Review",
    attendees: ["Sophie Reiter", "Jana Wolff", "Tobias Kramer"],
    description: "Vorstellung der Ergebnisse aus Sprint 24.",
  },
  {
    id: "personal-003",
    dayIndex: 3, // Do
    weekIndex: 0,
    timeLabel: "14:00",
    endTimeLabel: "14:30",
    title: "1:1 mit Sophie",
    attendees: ["Sophie Reiter"],
    recurring: true,
  },
  {
    id: "personal-004",
    dayIndex: 4, // Fr
    weekIndex: 0,
    timeLabel: "09:30",
    endTimeLabel: "10:00",
    title: "Weekly Retrospektive",
    attendees: ["Sophie Reiter", "Markus Haas", "Jana Wolff", "Miriam Schulte"],
    recurring: true,
  },

  // ── Pending invites — sent by a colleague, awaiting RSVP ──────────────────
  {
    id: "personal-invite-001",
    dayIndex: 1, // Di
    weekIndex: 0,
    timeLabel: "15:00",
    endTimeLabel: "16:00",
    title: "Roadmap Alignment Q3",
    attendees: ["Tobias Kramer", "Miriam Schulte", "Dominic Bechtold"],
    description: "Abstimmung der Roadmap-Prioritäten für Q3. Deine Einschätzung zu Feature X wäre hilfreich.",
    invitedBy: "Tobias Kramer",
    rsvp: "pending",
  },
  {
    id: "personal-invite-002",
    dayIndex: 2, // Mi
    weekIndex: 0,
    timeLabel: "10:00",
    endTimeLabel: "10:30",
    title: "Design Review: Onboarding Flow",
    attendees: ["Jana Wolff", "Dominic Bechtold"],
    description: "Jana möchte Feedback zum überarbeiteten Onboarding-Screen.",
    invitedBy: "Jana Wolff",
    rsvp: "pending",
  },
  {
    id: "personal-invite-003",
    dayIndex: 3, // Do
    weekIndex: 0,
    timeLabel: "16:00",
    endTimeLabel: "17:00",
    title: "Tech Debt Triage",
    attendees: ["Markus Haas", "Dominic Bechtold"],
    description: "Priorisierung offener Tech-Debt-Tickets vor dem nächsten Sprint.",
    invitedBy: "Markus Haas",
    rsvp: "pending",
  },

  // ── Next week (W+1) — one pending invite to show it also works across weeks ─
  {
    id: "personal-invite-004",
    dayIndex: 0, // Mo
    weekIndex: 1,
    timeLabel: "13:00",
    endTimeLabel: "14:00",
    title: "Customer Feedback Session",
    attendees: ["Miriam Schulte", "Tobias Kramer", "Dominic Bechtold"],
    description: "Live-Feedback-Runde mit zwei Bestandskunden. Bitte Notizen vorbereiten.",
    invitedBy: "Miriam Schulte",
    rsvp: "pending",
  },
];
