"""add company and personal desk tables

Revision ID: 7146f21e6688
Revises: bae331af7ba5
Create Date: 2026-07-01 22:01:41.636740

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7146f21e6688"
down_revision: Union[str, None] = "bae331af7ba5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("segment", sa.String(length=255), nullable=False),
        sa.Column("last_visited", sa.String(length=64), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("open_questions", sa.Integer(), nullable=False),
        sa.Column("completed_questions", sa.Integer(), nullable=False),
        sa.Column("pending_meetings", sa.Integer(), nullable=False),
        sa.Column("completed_meetings", sa.Integer(), nullable=False),
        sa.Column("portfolio_summary", sa.Text(), nullable=False),
        sa.Column("performance_summary", sa.Text(), nullable=False),
        sa.Column("assigned_roles", sa.JSON(), nullable=False),
        sa.Column("documents", sa.JSON(), nullable=False),
        sa.Column("hypotheses", sa.JSON(), nullable=False),
        sa.Column("appointments", sa.JSON(), nullable=False),
        sa.Column("notes", sa.JSON(), nullable=False),
        sa.Column("team_members", sa.JSON(), nullable=False),
        sa.Column("personas", sa.JSON(), nullable=False),
        sa.Column("newsfeed", sa.JSON(), nullable=False),
        sa.Column("recent_events", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personal_appointments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("day_index", sa.Integer(), nullable=False),
        sa.Column("week_index", sa.Integer(), nullable=False),
        sa.Column("time_label", sa.String(length=16), nullable=False),
        sa.Column("end_time_label", sa.String(length=16), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("attendees", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column("invited_by", sa.String(length=255), nullable=True),
        sa.Column("rsvp", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personal_colleagues",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("function_name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personal_colleagues")
    op.drop_table("personal_appointments")
    op.drop_table("companies")
    # ### end Alembic commands ###
