# Event types for behavior tracking
EVENT_CHAT_MESSAGE = "chat_message"
EVENT_RECOMMENDATION_VIEW = "recommendation_view"
EVENT_RECOMMENDATION_CLICK = "recommendation_click"
EVENT_DOCUMENT_UPLOAD = "document_upload"
EVENT_WEATHER_CHECK = "weather_check"
EVENT_PROFILE_UPDATE = "profile_update"
EVENT_NOTIFICATION_READ = "notification_read"
EVENT_LOGIN = "login"

ALL_EVENT_TYPES = [
    EVENT_CHAT_MESSAGE,
    EVENT_RECOMMENDATION_VIEW,
    EVENT_RECOMMENDATION_CLICK,
    EVENT_DOCUMENT_UPLOAD,
    EVENT_WEATHER_CHECK,
    EVENT_PROFILE_UPDATE,
    EVENT_NOTIFICATION_READ,
    EVENT_LOGIN,
]

# Intent labels
INTENT_WEATHER = "weather"
INTENT_RECOMMENDATION = "recommendation"
INTENT_DOCUMENT_SEARCH = "document_search"
INTENT_GENERAL_CHAT = "general_chat"
INTENT_PROFILE_UPDATE = "profile_update"
INTENT_HELP = "help"

ALL_INTENTS = [
    INTENT_WEATHER,
    INTENT_RECOMMENDATION,
    INTENT_DOCUMENT_SEARCH,
    INTENT_GENERAL_CHAT,
    INTENT_PROFILE_UPDATE,
    INTENT_HELP,
]

# Domain labels
DOMAIN_WEATHER = "weather"
DOMAIN_ENTERTAINMENT = "entertainment"
DOMAIN_TECHNOLOGY = "technology"
DOMAIN_HEALTH = "health"
DOMAIN_FINANCE = "finance"
DOMAIN_TRAVEL = "travel"
DOMAIN_GENERAL = "general"

ALL_DOMAINS = [
    DOMAIN_WEATHER,
    DOMAIN_ENTERTAINMENT,
    DOMAIN_TECHNOLOGY,
    DOMAIN_HEALTH,
    DOMAIN_FINANCE,
    DOMAIN_TRAVEL,
    DOMAIN_GENERAL,
]

# Notification types
NOTIFICATION_INFO = "info"
NOTIFICATION_SUCCESS = "success"
NOTIFICATION_WARNING = "warning"
NOTIFICATION_ERROR = "error"
